export const GET_ALL_USERS_DATA = 'GET_ALL_USERS_DATA';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_USER_REPOSITORIES = 'GET_USER_REPOSITORIES';
export const GET_FAVORITE_USER_REPOSITORIES = 'GET_FAVORITE_USER_REPOSITORIES';
   
export const GET_ALL_USERS_DATA_ERROR = 'GET_ALL_USERS_DATA_ERROR';
export const GET_USER_DATA_ERROR  = 'GET_USER_DATA_ERROR';
export const GET_USER_REPOSITORIES_ERROR  = 'GET_USER_REPOSITORIES_ERROR';
export const GET_FAVORITE_USER_REPOSITORIES_ERROR = 'GET_FAVORITE_USER_REPOSITORIES_ERROR';
